### DISCUSSION TITLE
[ProgressStepper] - indicate progress between (long-running) steps

### DISCUSSION THREAD

**Discussion by garrett** [patternfly/patternfly#5489] [Feature requests]
**Is this a new component or an extension of an existing one?**
Progress Stepper component

**Describe the feature**
Display in-between progress for steps that take a while.

For the new Anaconda (OS installation for Fedora, RHEL, CentOS, Alma, Rocky, etc.) implementation using PatternFly, during a usability test, there wasn't enough granular feedback for the process. The stepper component was used, but each step could take some time between several seconds to several minutes.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**

Here's a quick idea that would blend the progress bar experience into the progress stepper, so the stepper works as it does currently, but in-between progress shows up as a progress-bar-like line.
![PatternFly 4 • Progress stepper](https://user-images.githubusercontent.com/10246/178994267-7289450d-a58e-4e9d-b34b-be82bcaf91f2.png)

Source SVG: [Progress stepper.svg](https://user-images.githubusercontent.com/10246/178994279-fe6082c9-d108-4bd5-a2f2-e5bf618cd0e2.svg)

An additional idea is that we could even have a spinner on the current step. But that's probably overkill. :wink:

**Comment by mcoker** [comment]
cc @mcarrano @mmenestr

**Comment by mcarrano** [comment]
@garrett I can see the desire for this but is this a continuous process from start to end or does each step represent a stop along the way. i.e. to progress stop when I get to the end of a step and the user needs to intervene?

**Comment by shirimordechay** [comment]
You can use the current PF design with PF icons and combine the sub-steps for additional indications such as we use in OCM:
![image](https://user-images.githubusercontent.com/10331355/179390378-b12e894b-de0e-424e-b788-286372c365e9.png)

**Comment by garrett** [comment]
Firstly, reminder: This mockup was made as a response to a user study. PatternFly currently does not solve the issue in the study, so the installer team will either have to do something custom or rely on PatternFly to address the need of having a widget that communicates a long running, multi-step progress.

> @garrett I can see the desire for this but is this a continuous process from start to end or does each step represent a stop along the way. i.e. to progress stop when I get to the end of a step and the user needs to intervene?

It's for Anaconda. It installs Linux to a computer. 

Just like any other operating system installer (just like when installing Windows, macOS), it can take a very long time (such as half an hour; sometimes more, sometimes less) to install, depending on several different factors (especially disk speed; but sometimes network speed too, when it's downloading packages from a remote site).

Each step is along the way where the installer is doing something different. There's (usually) no user intervention in this long-running process, but each step can take different amounts of time to complete. (Some might take a minute or less, whereas others might be the bulk of the time, such as 10 - 30 minutes or even longer.) There is always user intervention at the end of the process, when the installation has either succeeded or failed (in which it still would show which step it has failed). There might need to be user intervention in a mid-step too (example: such as if the network went down while it was downloading packages during a network install; one could try again or the process could fail, depending). The final screen shows the status (success/fail), along with the step in the stepper, and that the user needs to reboot the system.

Knowing each step is important, as someone who has installed Linux before will know that some steps are longer (installing especially). The steps of the installer are, basically:

1. Partitioning the disk and formatting filesystems in partitions
   - some partitioning schemes take a while longer to set up (such as RAID) and/or when network storage is used (such as iSCSI)
2. Installing software packages to the disk
   - installing software usually takes the longest amount of time, especially when installing from the network or installing from a slow device (USB stick or DVD-ROM) and/or installing to a slow device (hard disk versus SSD or NVMe)
3. Configuring the system
4. Finalizing installation by making it able to boot
   - in this step, Anaconda is building a special booting filesystem (which can take a little while) called an initrd (initial ram disk) with initial hardware support so that it can load the rest from disk; this can be slow
   -  it then sets up the computer to boot through that using either a legacy method or UEFI; this is usually very quick and included in the same step

These are done in order and one step has to wait on the next.

If someone walks away form an installation to get coffee and they return and it's still installing software packages, they'll know it'll take a while longer. If it's finalizing installation, it might just be a minute or two before they have to tell the computer to reboot. If it fails in a step, it's important to know which step failed, as the resolution might be different (try again vs. replacing faulty hardware).

Right now, using the PF stepper component, it can sit there with absolutely no user feedback of progress, so the system looks like it has hung. (An indeterminate spinner doesn't help, either; one was used in the current PF-based Anaconda during the user study.)

**Basically:** Someone installing an OS on a computer needs feedback that it's still happening and that there is forward progression. The PF progress bar does not have steps (or even tickmarks) and the stepper does not show progress, and every single person in the user study commented on this problem... so this is why I'm suggesting this hybrid to solve the issue.

The normal component could even have the progression indicated in the line and circle part, to reinforce progress, even if it doesn't have partial lines between the items. (Especially because it's a little confusing where you are in the screenshots that @shirimordechay posted. But I guess the context of actually doing the process might help there?)

---

> You can use the current PF design with PF icons and combine the sub-steps for additional indications such as we use in OCM:

That's not the same thing at all. There's no progress between long-running steps in these screenshots, which is what this issue is about. I know the icons can be changed; the icons are basically placeholders in my mockup above... I didn't want to distract from the actual issue and solution, so I just used the default incomplete, current, & complete icons.

**Comment by mcarrano** [comment]
@garrett thanks for posting this detailed explanation. Having done many OS installs myself over the years, I get what the problem is, and think your proposed solution is a reasonable one. Before putting this on our feature roadmap, I think this would be a good topic to present in an upcoming design share meeting just to see if others have also encountered this and if there are other potential solutions we are not considering here. Those meetings are every third Wednesday at 11am EDT. Is it possible for you to be available to present this at that time? If not, I can present this on your behalf for feedback on your proposal. Let me know.

I am also going to move this issue over to Design for further consideration.

**Comment by garrett** [comment]
I've implemented the mockup in basically 5 lines of CSS (mainly to set colors and a width for percentage), where the percentage is exposed as a number (representing a percentage), which React can modify.

Demo:
https://codesandbox.io/s/unruffled-benji-cx657r?file=/progress-demo.scss

Screenshot:

![stepper progress](https://user-images.githubusercontent.com/10246/181002618-7867dd8a-9566-4856-9641-2da09e0fb264.png)


---

Most of the content below are pulled directly from [PatternFly's basic demo for the stepper](https://www.patternfly.org/v4/components/progress-stepper#basic), in JSX. We'd probably want to set the progress colors to the same color, like a progress color variable (unless we want past, active, and future to be the same). In the mockup, I merged the colors of past and current and leave future the default color. In the demo, I used green and red for past and current, respectively. I do not suggest using green and red in the actual implementation; they're for demonstration purposes only.

When progress isn't set, the width between steps is 0%, so it works by default to indicate past and current step, but not current progress.

Additionally, the `::after` could have a CSS transition set for width so for smooth animation can be handled by CSS (therefore GPU accelerated), so when something jumps from 25% to 63% (or whatever), it won't just jump, but smoothly move.

Current progress is relative to the step, not the overall progress.

SCSS:

```scss
// Example CSS
.pf-m-success {
  // Demo colors
  --pf-c-progress-stepper__step-icon--BorderColor: green;
  --pf-c-progress-stepper__step-connector--before--BorderBottomColor: green;
}

.pf-m-current {
  // Another demo color (could be the same as the success colors)
  --pf-c-progress-stepper__step-icon--BorderColor: red;
}

.pf-c-progress-stepper__step:not(:last-of-type) > .pf-c-progress-stepper__step-connector::after {
  // Unique to ::after
  --pf-c-progress-stepper__step-connector--before--BorderBottomColor: red;
  width: calc(var(--pf-c-progress-stepper__step-percent) * 1%);

  // /////////////////////////////////////////////////////////////
  // Shared in common with ::before (from PF)
  position: absolute;
  top: var(--pf-c-progress-stepper__step-connector--before--Top);
  left: var(--pf-c-progress-stepper__step-connector--before--Left);
  height: var(--pf-c-progress-stepper__step-connector--before--Height);
  content: "";
  border-right: var(--pf-c-progress-stepper__step-connector--before--BorderRightWidth) solid var(--pf-c-progress-stepper__step-connector--before--BorderRightColor);
  border-bottom: var(--pf-c-progress-stepper__step-connector--before--BorderBottomWidth) solid var(--pf-c-progress-stepper__step-connector--before--BorderBottomColor);
  transform: var(--pf-c-progress-stepper__step-connector--before--Transform);
}
```

JSX:

```jsx
import ReactDOM from "react-dom";
import "@patternfly/react-core/dist/styles/base.css";
import "./fonts.css";
import "./progress-demo.scss";

import React from "react";
import { ProgressStepper, ProgressStep } from "@patternfly/react-core";

const Basic = () => (
  <ProgressStepper>
    <ProgressStep
      variant="success"
      id="basic-step1"
      titleId="basic-step1-title"
      aria-label="completed step, step with success"
    >
      First step
    </ProgressStep>
    <ProgressStep
      variant="info"
      isCurrent
      id="basic-step2"
      titleId="basic-step2-title"
      aria-label="step with info"
      // Implemented here as a style, so I didn't have to change any PF JS;
      // ideally, it would be exposed as a property
      style={{ "--pf-c-progress-stepper__step-percent": 50 }}
    >
      Second step
    </ProgressStep>
    <ProgressStep
      variant="pending"
      id="basic-step3"
      titleId="basic-step3-title"
      aria-label="pending step"
    >
      Third step
    </ProgressStep>
  </ProgressStepper>
);

const rootElement = document.getElementById("root");
ReactDOM.render(<Basic />, rootElement);
```

**Comment by garrett** [comment]
I've made a modified second demo which has closer-to-ready SCSS (tying it to the widget), adding it as a pf-m- variant, uses success and current colors, and adds a transition:

https://codesandbox.io/s/staging-dream-6wrzt8?file=/progress-demo.scss

It adds a className to the topmost widget and changes the SCSS to:

```scss
.pf-c-progress-stepper.pf-m-show-progress {
  --pf-c-progress--SuccessColor: green;
  --pf-c-progress--CurrentColor: red;

  .pf-c-progress-stepper__step {
    &.pf-m-success {
      // Demo colors
      --pf-c-progress-stepper__step-icon--BorderColor: var(--pf-c-progress--SuccessColor);
      --pf-c-progress-stepper__step-connector--before--BorderRightColor: var(--pf-c-progress--SuccessColor);
      --pf-c-progress-stepper__step-connector--before--BorderBottomColor: var(--pf-c-progress--SuccessColor);
    }
  
    &.pf-m-current {
      // Another demo color (could be the same as the success colors)
      --pf-c-progress-stepper__step-icon--BorderColor: var(--pf-c-progress--CurrentColor);
    }  
  }

  .pf-c-progress-stepper__step:not(:last-of-type) > .pf-c-progress-stepper__step-connector::after {
    // Unique to ::after
    --pf-c-progress-stepper__step-connector--before--BorderBottomColor: var(--pf-c-progress--CurrentColor);
    --pf-c-progress-stepper__step-connector--before--BorderRightColor: var(--pf-c-progress--CurrentColor);
    width: calc(var(--pf-c-progress-stepper__step-percent, 0) * 1%);
    transition: width 500ms ease-out;

    // /////////////////////////////////////////////////////////////
    // Shared in common with ::before (from PF); PF CSS should be modified to share this with ::before
    position: absolute;
    top: var(--pf-c-progress-stepper__step-connector--before--Top);
    left: var(--pf-c-progress-stepper__step-connector--before--Left);
    height: var(--pf-c-progress-stepper__step-connector--before--Height);
    content: "";
    border-right: var(--pf-c-progress-stepper__step-connector--before--BorderRightWidth) solid var(--pf-c-progress-stepper__step-connector--before--BorderRightColor);
    border-bottom: var(--pf-c-progress-stepper__step-connector--before--BorderBottomWidth) solid var(--pf-c-progress-stepper__step-connector--before--BorderBottomColor);
    transform: var(--pf-c-progress-stepper__step-connector--before--Transform);
  }
}
```
