### DISCUSSION TITLE
Disabling nav item

### DISCUSSION THREAD

**Discussion by uzytkownik** [patternfly/patternfly#5660] [Q&A]
Hi,

I'm not sure if it is a feature request or lack of documentation - but how to have a disabled nav item?

**Comment by mcarrano** [comment]
@uzytkownik we do not currently support disabling navigation items. Can you say more about your use case and why you need this?

**Comment by uzytkownik** [comment]
I'm writing a one page application. Most options are unavailable unless state is created.

I managed to use:

```html
<li class="pf-c-nav__item">
    <span class="pf-c-nav__link my-app-disabled">
        ...
     </span>
</li>
```

and

```scss
.my-app-disabled {
    color: #6a6e73;
}

.my-app-disabled:hover {
    color: #6a6e73;
}

```

to disable an item.
