### ISSUE TITLE
tables: Animate expanding rows

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#3053]
In Cockpit, we've animated the expanding rows for some time now.

Since we're porting to PF4 tables instead of using PF3 ones, we've needed to port our quick expanding animation too, which animates with the already rotating expander icon (">").

It currently looks like this:

```scss
@media not all and (prefers-reduced-motion: reduce) {
  // Add expansion animations when prefers-reduced isn't enabled
  .ct-table .pf-c-table__expandable-row-content {
    // Animation ends at or before 2/3 in most cases; so we extend by 1.5 to compensate
    animation: ctListingPanelShow calc(var(--pf-global--TransitionDuration) * 1.5) var(--pf-global--TimingFunction);
  }
}

@keyframes ctListingPanelShow {
  0% {
    // The animation needs to flow downward to feel natural
    transform-origin: top;
    // Overflow will revert when done (but should be hidden during animation)
    overflow: hidden;
    max-height: 0;
    // Padding should 'tween between 0 and the actual padding (unstated)
    padding-top: 0;
    padding-bottom: 0;
  }
  67% {
    // Max height is tricky in animations, as auto doesn't work
    // 100vh makes sense, but would cause different speeds on different devices
    // Screens are almost all =< 12000px; data is almost always smaller
    // we'll relax it to to 100vh at 100%, just in case.
    max-height: 1200px;
  }
  100% {
    // Allow content to extend to the height of the screen (just in case)
    max-height: 100vh;
  }
}
```

(We've added a `ct-table` class, so we can target the widget with our own custom CSS in our PF4-based custom widget without having to override PF everywhere.)
