### ISSUE TITLE
alert: Actionable alerts are cramped in mobile views.

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#3125]
When alerts have actions that are not simply a dismiss with an × icon, the content is displayed in a very subsumption manner on mobile.

A Cockpit-specific issue is at https://github.com/cockpit-project/cockpit/issues/14106.

Problem | Solution
---|---
![81177985-cbd0f180-8fa7-11ea-9e50-5667b6dd6737](https://user-images.githubusercontent.com/10246/82230894-a2f81700-992c-11ea-895e-b9c4e24154ed.png) | ![Screen Shot 2020-05-18 at 17 03 12](https://user-images.githubusercontent.com/10246/82230890-a25f8080-992c-11ea-97e2-7c453b41b384.png)

I quickly wrote a bit of SCSS to fix the issue with the (restyled) banner at the top of our page that basically looks like:

```scss
@media (max-width: $mobile) {
  .pf-c-alert {
    grid-template-areas: "icon title" ". content" ". action";
    grid-gap: var(--pf-global--spacer--sm) 0;
  }
}
```

But, it's not generic! As you can see in the comparison, the MOTD notice at the bottom has the × icon moved to the end. I'm pretty sure nobody wants that. :wink:

We'd need to have a class like `pf-m-actionable` (or whatever it might be called) added to the top of the alert element and change the grid layout based on that. Alternatively, dismissable alerts could have `pf-m-dismissable` instead.

For the time being, I'm going to suggest that Cockpit have a local override, but this is something that other projects could benefit from.
