### ISSUE TITLE
Multine clipboard copy doesn't work

### ISSUE THREAD

**Issue by hguerrero** [patternfly/patternfly#3272]
When having multiline extended blocks the copy clipboard command removes formatting line new lines, spaces and tabs.

**Comment by mcoker** [comment]
@hguerrero can you recreate this in a codesandbox? You can find the codesandbox links under each example on https://www.patternfly.org/v4/documentation/react/components/clipboardcopy (react) and https://www.patternfly.org/v4/documentation/core/components/clipboardcopy (core - html/css)

**Comment by hguerrero** [comment]
Here is an example: https://codesandbox.io/s/white-night-pq0j3?file=/index.html the text should be copied with the indentation (as is YAML) 

```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: amq
spec:
  plan: standard-small
  type: standard
  endpoints:
    - name: messaging
      service: messaging
      expose:
        type: route
        routeServicePort: amqps
        routeTlsTermination: passthrough
      exports:
        - kind: ConfigMap
          name: amq-config
  authenticationService:
    name: none-authservice
```
