### ISSUE TITLE
Alert title font size is unspecified and often incorrect when PF4 is mixed with other frameworks (including PF3)

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#4004]
The PatternFly 4 alert title (`.pf-c-alert__title`) does not specify a font size (or even family). PatternFly assumes that this will be inherited from `.pf-c-alert`.

However, when other frameworks, which often specify a font-size and sometimes a different font-family are used in a project that also uses PatternFly 4, the alert fonts have the H4 styling applied instead.

The solution is to directly specify which font styling the title should use. As the title is assumed to use the alert's default styling, it should inherit (instead of setting a size itself).

Related: https://github.com/cockpit-project/cockpit/issues/15639

**Comment by garrett** [comment]
Here's an example of a warning from a current PR about live migration of virtual machines in some circumstances:

![Screenshot_2021-04-14 Virtual Machines - garrett Rain(1)](https://user-images.githubusercontent.com/10246/114707280-4fec3700-9d2a-11eb-90be-d248c56d8772.png)

The alert sizing should, of course, look like this (from the PF4 docs):

![Screenshot_2021-04-14 PatternFly 4 • Alert](https://user-images.githubusercontent.com/10246/114707267-4c58b000-9d2a-11eb-9d89-843a1b81ef6d.png)

---

[The fix we're implementing in our PatternFly 4 overrides file](https://github.com/cockpit-project/cockpit/pull/15693/files#diff-325ba8d07b7191456e22e2785c61be383372356c4e38b9a7cbfe35021be2af96R122-R128) is this:

```scss
// Alerts use elements that have fonts set in other frameworks (including PF3);
// generally, this is an H4 that often has a font size and sometimes family set.
// Therefore, it should inherit from the alert font set at the pf-c-alert level.
.pf-c-alert__title {
    font: inherit;
}
```

**Comment by garrett** [comment]
Note: we changed this to font-size: inherit; font-family: inherit; to be more specific, as in some cases (in Cockpit), the font weight was actually supposed to be heavier (bold instead of default).

Here's the latest CSS in our pending Cockpit-specific PR:

https://github.com/cockpit-project/cockpit/pull/15693/files#diff-325ba8d07b7191456e22e2785c61be383372356c4e38b9a7cbfe35021be2af96R122-R129

```scss
// Alerts use elements that have fonts set in other frameworks (including PF3);
// generally, this is an H4 that often has a font size and sometimes family set.
// Therefore, it should inherit from the alert font set at the pf-c-alert level.
// https://github.com/patternfly/patternfly/issues/4004
.pf-c-alert__title {
    font-size: inherit;
    font-family: inherit;
}
```
