### ISSUE TITLE
request: list select, similar to <select multiple>

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#4027]
We've been using some list select widgets, implemented with <select multiple> for some time in Cockpit. In most cases, we only have one item selected at a time. In others, we allow multiple selections.

**Comment by garrett** [comment]
GitHub is acting funky and stripped all formatting and images, making the feature request hard to read and understand. I'll try to correct here.

It looked like this before:
![114021483-0c4c8580-9871-11eb-90f9-257c8f73ef8d](https://user-images.githubusercontent.com/10246/116102516-106d0580-a6af-11eb-9139-1c2f69300281.png)

Some of the devs used the _menu_ component (which is wrong, but has the functionality we're looking for):
![114021588-25553680-9871-11eb-8d85-b4d58145b1a7](https://user-images.githubusercontent.com/10246/116102511-0fd46f00-a6af-11eb-9828-08ec00a81f4b.png)

I mad some CSS to override the style a bit, to make it look like what a list select widget might look like:
![116096952-fed52f00-a6a9-11eb-9e4d-05aa1523264c](https://user-images.githubusercontent.com/10246/116102518-106d0580-a6af-11eb-8c99-ea138ed152b4.png)

**Comment by KKoukiou** [comment]
Some of the devs; /me hiding

**Comment by garrett** [comment]
I wasn't pointing fingers. :point_left: :point_up: :point_right:  :wink:

**Comment by garrett** [comment]
I'd imagine that we should have the default version without the filter, but have an option to have a filter above it too, like pictured above.

It would also be similar to the new treeview, but without the tree. I'm not sure how much this could inherit from the menu or the treeview, but perhaps we can build it off of the parts of one or both of them? _Or_ make a special mode in the treeview that would do this selection too?

**Comment by mcoker** [comment]
@garrett have you looked at the simple list component? https://www.patternfly.org/v4/components/simple-list

cc @mcarrano

**Comment by garrett** [comment]
Oh, I hadn't considered simple list, but it does have these issues that make it not quite right either:

- font size is `sm` instead of the normal `md`
- it wasn't obvious that it should be used for a scrolling a long list of items
- there's no frame around it indicating that it's a region (especially important when scrolling)
- there isn't a way to ask for a search area above it for filtering
- the style where a selected item becomes bold is a bit different from the rest of PF? (various selected items get one or more of the following: background highlight, check next to them, and/or bold)

That said, perhaps this widget could be extended with options. It does seem to be the most similar in spirit to what we want. But then it wouldn't be so "simple" anymore. :wink: Perhaps we could call it a "select list"?

**Comment by mcarrano** [comment]
@garrett what is wrong with using the Menu component? https://www.patternfly.org/v4/components/menu#option-single-select  Is it just that the styling is designed for use in a dropdown (has a drop shadow)?

**Comment by garrett** [comment]
@mcarrano: Using the Menu component is exactly what we're currently doing, with some overrides to the styling and a fix for the focus/selected state @ https://github.com/cockpit-project/cockpit/pull/15749

... specifically https://github.com/cockpit-project/cockpit/pull/15749/files#diff-fd6771d9d7322a733e4bf643b938d0151d0739c7aed2e1028a4dbf056d0bac0fR6-R35:

```scss
.ct-menu-select-widget.pf-c-menu {
    // It's  not really a menu, so it shouldn't have a shadow
    box-shadow: none;

    // Divider is silly between the widgets in this context
    .pf-c-divider {
        display: none;
    }

    .pf-c-menu__content {
        // An overflow multi-select widget needs an outline
        border: 1px solid var(--pf-global--BorderColor--100);
        // There should be minimal space between the widgets (replacing the divider)
        margin-top: var(--pf-global--spacer--sm);
    }

    // Search should not be inset when there's no border containing it
    .pf-c-menu__search {
        padding: 0;
    }

    // Keep the background on a selected item even when it doesn't have
    // focus, allowing keyboard control to have the only background color
    // when active but also keep the background color when the list loses
    // focus (such as when the keyboard or mouse navigates outside,
    // including initial rendering of the list.
    .pf-c-menu__list:not(:focus-within) .pf-m-selected {
        background-color: var(--pf-c-menu__list-item--hover--BackgroundColor);
    }
}
```

The `:focus-within` block at the bottom is the fix. It's probably not a big deal for PF to handle the focus change for a menu, as the menu is transient and our selection is not. (That is, the menu will go away when someone focuses anything else. Our selection menu will have someone clicking or tabbing elsewhere, including the modal's action buttons.)

We think it's probably a good idea to have a widget like this for other places within Cockpit and for other teams outside of Cockpit, hence opening this request.

If something similar is implemented within PatternFly, we could switch to it. It's fine if it's a optionally modified version of Menu, (a treeless) Treeview, Simple List. It's also fine if it's a different widget on its own too.
