### ISSUE TITLE
Toolbar: when using the toggle version of the toolbar filters the toolbar unnecessarily takes too much vertical space

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#4115]
Current patternfly:

![Screen Shot 2021-06-02 at 09 46 55](https://user-images.githubusercontent.com/14921356/120286453-8b34cc00-c2be-11eb-803e-95171c83d6ef.png)

Expected result:

![Screen Shot 2021-06-02 at 09 46 38](https://user-images.githubusercontent.com/14921356/120286456-8bcd6280-c2be-11eb-90ae-9ea61f08c9db.png)

Since we are dealing here with mobile mode, a few pixels are important to be saved. Our designer added some custom CSS to achieve this result. The CSS follows:
``` css

// Wrap the filter info
.services-toolbar.pf-c-toolbar {
    display: flex;
    flex-wrap: wrap;
    border-bottom: 1px solid var(--pf-global--BorderColor--100);

    > .pf-c-toolbar__content:first-child {
        flex: auto;
    }

    .pf-c-toolbar__content-section {
        width: auto;
    }
}
```

**Comment by mcoker** [comment]
cc @mcarrano @mattnolting

**Comment by garrett** [comment]
I have since updated the CSS to only apply to the status message (in small screen devices), leaving the chip group always below the filter entries.

https://github.com/cockpit-project/cockpit/blob/d19bccbd2a05bc656d98d5efbed653aa4a761697/pkg/lib/patternfly/patternfly-4-overrides.scss#L145-L160:

```scss
.pf-c-toolbar {
    // ... //

    // Make summary content use the same vertical space as the filter toggle,
    // when possible.
    // https://github.com/patternfly/patternfly/issues/4115
    &.ct-compact {
        @media screen and (max-width: $pf-global--breakpoint--lg - 1) {
            display: flex;
            flex-wrap: wrap;

            > .pf-c-toolbar__content:first-child {
                flex: auto;
            }

            .pf-c-toolbar__content-section {
                width: auto;
            }
        }
    }
}
```
