### ISSUE TITLE
dropdown: Masthead dropdowns have a residual focus/active line after dismissing the menu with a mouse

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly#4534]
When a dropdown is in the masthead, a line should show up when hovering and when the menu is active. When the menu is dismissed, the line should disappear. However, it doesn't. (This should not affect keyboard focus, however.)

Here's a video to show the issue:

https://user-images.githubusercontent.com/10246/142893848-05514356-6a22-4850-b1dc-af08a15c46eb.mp4
(The line is actually blue, not grey. There's a glitch when I recorded it. It's blue on-screen.)

The fix, which I'm adding to Cockpit right now as a workaround, is:

```scss
// In masthead dropdowns, hide line when focus-activated by a mouse
// But still show the line when a keyboard focuses or a mouse hovers or clicks
.pf-c-masthead .pf-c-dropdown:not(.pf-m-expanded) > .pf-c-dropdown__toggle:focus:not(:focus-visible):not(:hover):not(:active)::before {
    border-color: transparent;
}
```

Yes, this has a lot of modifiers. Hopefully the comment helps to walk through. Most importantly, this does not affect keyboard focus.

This would impact https://github.com/patternfly/patternfly/issues/3844, as the style would be altered, but the technique to undo the state would be the same.
