### ISSUE TITLE
Page with drawer - collapsed sidebar layout issue

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#7126]
Reported by @jeff-phillips-18 

I’m seeing an issue when trying to close the nav bar via the page toggle. I see two settings in the css:

```css
.pf-v6-c-page__main-container,
.pf-v6-c-page__drawer {
  z-index: var(--pf-v6-c-page__main-container--ZIndex);
  grid-area: var(--pf-v6-c-page__main-container--GridArea);
  overflow-x: hidden;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

[...]
.pf-v6-c-page__drawer {
  grid-area: main;
}
```

I believe the latter is incorrect and causing the nav bar to still take up space. The Page documentation uses the .pf-v6-c-page__main-container so it is not exhibiting the problem.

<img width="1706" alt="Screenshot 2024-09-27 at 5 02 12 PM" src="https://github.com/user-attachments/assets/61ad417b-d08b-49f4-9eca-9349d27573bf">
