### ISSUE TITLE
Inline link button - hover color, text decoration, and icon

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#7221]
Add variables to support theming of inline link buttons.
```css
.pf-v6-c-button.pf-m-link.pf-m-inline {
 text-decoration-color: var(--mui-link-underlineColor);
 color:  is var needed?

 &:hover {
   // PF can introduce this customization, needs input from design first
   text-decoration-color: initial;
 }
}
.pf-v6-c-button.pf-m-link.pf-m-inline .pf-v6-c-button__icon {
 // PF to provide the inline link icon color variable
 color: inherit;
}

```
