### ISSUE TITLE
Check - Introduce block-size option in forms

### ISSUE THREAD

**Issue by Venefilyn** [patternfly/patternfly#7411]
**Is this a new component or an extension of an existing one?**
Check component

**Describe the feature**
In Cockpit we have an inline form with a checkbox in it like this as we want it compact. However, PatternFly doesn't have a way of aligning the check with the other components. When we used PFv5 we had a rule that made it look like this:

![image](https://github.com/user-attachments/assets/5958a433-cb6a-4fdf-a901-4c5b3ff82ac9)

Within PFv6 here is a before and after the change to see how it makes the UX a lot better:

![image](https://github.com/user-attachments/assets/a909c356-fcd8-4c02-8d06-c7dba140e359)

For [Cockpit we've created an override for this](https://github.com/cockpit-project/cockpit/blob/6d00f474208fc6322c93d47f2e161e074dd557bd/pkg/lib/cockpit-components-dynamic-list.scss#L21-L29) that gets the font and line height to make it aligned horizontally with the other form components.

```css
.pf-v6-c-form__group-control>.pf-v6-c-check {
    // Set height to the same as inputs
    // Font height is font size * line height (1rem * 1.5)
    // Widgets have 5px padding, 1px border (top & bottom): (5 + 1) * 2 = 12
    // This all equals to 36px
    block-size: calc(var(--pf-t--global--font--size--md) * var(--pf-v6-global--LineHeight--md) + 12px);
    align-content: center;
}
```

---

**Jira Issue:** [PF-1357](https://redhat.atlassian.net/browse/PF-1357)
