### ISSUE TITLE
Bug - Table - Selectable table has checkbox misaligned

### ISSUE THREAD

**Issue by Venefilyn** [patternfly/patternfly#7424]
**Describe the problem**
This is an issue with 

- [ ] Patternfly 5  

- [x] Patternfly 6  

- [ ] other

With the Table component we have a select checkbox `.pf-v6-c-table__check` that doesn't align properly with the text in adjacent table row cells. This occurs both on normal and compact tables.

**How do you reproduce the problem?**
See selectable with checkbox
https://www.patternfly.org/components/table#selectable-with-checkbox

**Expected behavior**
The checkbox is center aligned with the text.

**Is this issue blocking you?**
No, workaround for us is this. I'd use a spacer but there was none for 0.125rem (which nicely adds it up to 10px and 18px for compact and default)

```css
.pf-v6-c-table__td.pf-v6-c-table__check {
  padding-block-start: calc(var(--pf-v6-c-table--cell--PaddingBlockStart) + 0.125rem)
}
```

**Screenshots**
compact

![image](https://github.com/user-attachments/assets/16470605-03ac-4de2-b231-cd35480d2835)

default

![image](https://github.com/user-attachments/assets/2d63bc89-f91d-484d-b66a-615b5878575d)

**What is your environment?**

- OS: Linux

- Browser Chromium

- Version 134.0.6998.165

---

**Jira Issue:** [PF-1389](https://redhat.atlassian.net/browse/PF-1389)
