### ISSUE TITLE
Bug - Helper Text - CSS Validation Error

### ISSUE THREAD

**Issue by logonoff** [patternfly/patternfly#7426]
**Describe the problem**
This is an issue with 
- [ ] Patternfly 5  
- [x] Patternfly 6  
- [ ] other

Please give a clear and concise description of the problem. Which components are affected?

form helper text

**How do you reproduce the problem?**
Provide steps to reproduce. A [codepen](http://codepen.io) or [codesandbox](https://codesandbox.io/) demonstrating the problem is appreciated.

I am getting CSS validation errors on https://validator.w3.org/ when using PatternFly CSS, particularly with this snippet:

```css
.pf-v6-c-helper-text__item.pf-m-error {
  --pf-v6-c-helper-text__item-text--FontWeight: var(--pf-v6-c-helper-text__item-text--m-error--FontWeight);
  --pf-v6-c-helper-text__item-icon--Color: var(--pf-v6-c-helper-text__item-icon--m-error--Color);
  animation-name: --pf-v6-c-helper-text-item-fade-in;
  animation-duration: var(--pf-v6-c-helper-text__item--m-error--TransitionDuration--Opacity);
  animation-timing-function: var(--pf-v6-c-helper-text__item--m-error--TransitionTimingFunction--Opacity);
}
@keyframes --pf-v6-c-helper-text-item-fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```

**Expected behavior**
A clear and concise description of the expected behavior.

The animation name is not prefixed with two dashes as that is explicitly forbidden: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name#values

> [<custom-ident>](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident)
>
>    An unquoted name identifying the animation. This identifier is composed of a combination of case-sensitive letters a to z, numbers 0 to 9, underscores (_), and/or dashes (-). The first non-dash character must be a letter. Also, two dashes are forbidden at the beginning of the identifier. Furthermore, the identifier can't be none, unset, initial, or inherit.

**Is this issue blocking you?**
List the workaround if there is one.

Sort of..? Would like to get this in before 6.2.0 GA

**Screenshots**
If applicable, add screenshots to help explain the issue.

![Image](https://github.com/user-attachments/assets/8436376e-35eb-4965-9e8d-c3c1a05d7db6)

**What is your product and what release date are you targeting?**

OCP Console 4.19
