### ISSUE TITLE
Spike - investigate use of light-dark()

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#7489]
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark
https://caniuse.com/?search=light-dark

Technically we will want to wait until Safari 19 to use, but we can look at it for now. This would likely simplify our CSS a bit and my hunch is that it would be more performant, too. If used in our component styles, it may also make it easier to assign light/dark themed blocks in PF, instead of having to declare the whole page (at `:root`) as light or dark

`light-dark` will follow `color-scheme`, so as long as `.pf-v6-theme-dark` sets `color-scheme: dark`, then we can use the following setup:

```css
:root {
  --token-1: light-dark(var(--token-1-light), var(--token-1-dark));
  --token-2: light-dark(var(--token-2-light), var(--token-2-dark));
  --token-3: light-dark(var(--token-3-light), var(--token-3-dark));
}

.pf-v6-theme-dark {
  color-scheme: dark;
}
```

Instead of

```css
:root {
  --token-1: var(--token-1-light);
  --token-2: var(--token-2-light);
  --token-3: var(--token-3-light);
}

.pf-v6-theme-dark {
  color-scheme: dark;
  --token-1: var(--token-1-dark);
  --token-2: var(--token-2-dark);
  --token-3: var(--token-3-dark);
}
```
